# Generated by Django 5.0.3 on 2024-03-15 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва')),
                ('img', models.ImageField(default='product/avatar_crj2ayQ.jpg', upload_to='avatar')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна товару')),
                ('discont', models.DecimalField(decimal_places=0, max_digits=100, verbose_name='Знижка')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Гаманець'),
        ),
        migrations.CreateModel(
            name='ProductKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keys', models.TextField(blank=True, verbose_name='Ключ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.products', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Ключі',
                'verbose_name_plural': 'Ключі',
            },
        ),
    ]
