# Generated by Django 5.0.3 on 2024-03-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_remove_question_datetime_question_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': '📊 Поширене запитання', 'verbose_name_plural': '📊 Поширені запитання'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '💢 Запитання', 'verbose_name_plural': '💢 Запитання'},
        ),
    ]
