# Generated by Django 5.0.3 on 2024-03-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_alter_faq_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='secret',
            field=models.CharField(default='', max_length=100, verbose_name='Секрет'),
        ),
    ]
