# Generated by Django 5.0.3 on 2024-03-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_userprofile_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('question', models.TextField(blank=True, verbose_name='Питання')),
                ('answer', models.TextField(blank=True, verbose_name='Відповідь')),
            ],
            options={
                'verbose_name': '⏳ Питання по режимам',
                'verbose_name_plural': '⏳ Питання по режимам',
            },
        ),
        migrations.CreateModel(
            name='RareQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('question', models.TextField(blank=True, verbose_name='Питання')),
                ('answer', models.TextField(blank=True, verbose_name='Відповідь')),
            ],
            options={
                'verbose_name': '🕗 Рідкісні питання',
                'verbose_name_plural': '🕗 Рідкісні питання',
            },
        ),
    ]
