# Generated by Django 5.0.3 on 2024-03-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbuying',
            name='secret',
            field=models.CharField(default='', max_length=100, verbose_name='Секрет'),
        ),
    ]
